### ISSUE TITLE
Lin Reg Outputs/Repo Organization

### ISSUE THREAD

**Issue by lucymosquera** [STAT547-UBC-2019-20/group_07#8]
Wondering what makes the most sense for output location for linear regression. The plot totally makes sense to go to the "images" folder, but I'm not sure where makes the most sense to store the RDS files of the model. They aren't really "data" but they definitely don't look like "scripts" or "images" either.

I set up the linear regression script to be flexible and save them in different places if desired.

**Comment by Deni678** [comment]
> Wondering what makes the most sense for output location for linear regression. The plot totally makes sense to go to the "images" folder, but I'm not sure where makes the most sense to store the RDS files of the model. They aren't really "data" but they definitely don't look like "scripts" or "images" either.
> 
> I set up the linear regression script to be flexible and save them in different places if desired.

sounds good!
