### ISSUE TITLE
Assignment 3 Peer Review for Milestone 2

### ISSUE THREAD

**Issue by almas2019** [STAT547-UBC-2019-20/group_07#9]
## Is the repository organized in a useful and sensible way?
- Yes it seems to be following the recommended folders. Except the misc folder could potentially be described better in the Readme. 
## Is there a Usage section in the README?
- Yes I do see the usage section. I would recommend using the code chunk formatting in the usage section to separate code from comments. 
## Do the scripts run to completion as described in the README?
- Yes the scripts ran for me and the instructions were clear. 
## Do the scripts produce the expected output?
- Yes I saw the expected graphs and files.
##  Are the scripts and functions appropriately documented?
- Yes its fairly clear in the scripts what each function does.
 ## Does it take a long time for the analysis to run? Are there tasks that could be vectorized to make things faster?
- Scripts were not slow. But I think in your clean.R script for example, I noticed you used the rename_at multiple times, and this could have been vectorized. Other places that it could have been vectorized were in your plots when you produced 2 scatterplots. Definitely recommend going into your scripts and looking at repetitive elements which could benefit from vectorization.  
## Are the research questions appropriate and well-chosen?
- Research questions seem appropriate, but it would be good to define what is meant by prevalent sentiments as this part seems vague (positive sentiments, or how a user feels?). Also I recommend focussing on a few variables to explore instead of the many you state as it can be good to have a more focused exploration.
## Are the visualizations effectively displayed? How can they be improved?
- I would recommend making the visualizations bigger as they seem fairly small in the report. I really liked the figure captions that you included.  
- Use geom_jitter for your scatterplots as the points seem to clump together. 
## Are there other, more effective visualizations that could or should be used? 
- I would recommend a different way to display your variables in your analysis(section 2.1) as it seems like a large list of variables. I would recommend a table similar to the demo that contains the variable and describes what information the variable captures , like what does congress.classifications mean for ex. ?

**Comment by lucymosquera** [comment]
Thanks @almas2019 ! We really appreciate the detailed feedback, especially the suggestion of making code in the README look like lines of code. Super helpful to learn how to do it! Will also look into your feedback & suggestions for the visualizations.

Thanks again!
